language: node_js
node_js:
  - "0.12"
addons:
  hosts:
    - banquet.notadomain.com
before_script:
  - "npm install -g bower"
  - "bower install"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
